{
  "openapi": "3.0.0",
  "info": {
    "title": "Employee Reward Sytem",
    "description": "This system has shows results for logged-in employee, his/her assigned tasks, and the Rewards Info - Employee of the day, Employee of the Week,and Employee of The Month",
    "version": "1.0.0",
    "contact": {
      "name": "Preeti Gupta",
      "email": "ppreeti.guptaa@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:5000/api/v1.0",
      "description": "Local server"
    }
  ],
  "paths": {
    "/rewards/{rewardType}?date={date}": {
      "get": {
        "summary": "Returns Employee Information For Employee of Day",
        "tags": ["Rewards"],
        "description": "This API will return Employee For Given Reward Type.",
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "rewardType",
            "required": true,
            "schema": {
              "enum": [
                "employee-of-the-day",
                "employee-of-the-week",
                "employee-of-the-month"
              ]
            },
            "description": "Reward Type"
          },
          {
            "in": "path",
            "name": "date",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Date for which to find Reward"
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON object of Employee of Day",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EmpOfDay"
                },
                "example": {
                  "rewardType": "employee-of-the-day",
                  "data": {
                    "id": 20,
                    "name": "Employee 20",
                    "designation": "Marketing Manager",
                    "email": "employee.20@peaksoft.com",
                    "date": "2022-02-22"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/employees": {
      "post": {
        "summary": "Create New Employee",
        "tags": ["Employees"],
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "required": true
                  },
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "designation": {
                    "type": "string",
                    "required": true
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "A json object of Employee details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "designation": {
                      "type": "string"
                    },
                    "bonusStars": {
                      "type": "integer"
                    },
                    "empOfDayCount": {
                      "type": "integer"
                    },
                    "empOfWeekCount": {
                      "type": "integer"
                    },
                    "empOfMonthCount": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                  "id": "EMPK-1",
                  "name": "Employee 1",
                  "email": "employee.1@peaksoft.com",
                  "designation": "Accountant",
                  "bonusStars": 0,
                  "empOfDayCount": 0,
                  "empOfWeekCount": 0,
                  "empOfMonthCount": 0
                }
              }
            }
          },
          "500": {
            "description": "A json object of error details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "message": {
                      "type": "string"
                    },
                    "reason": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "messsage": "Error",
                  "reason": "\"name\" must be a string ; \"email\" must be a valid email ; \"designation\" must be a string"
                }
              }
            }
          }
        }
      }
    },
    "/employees/{employeeId}": {
      "get": {
        "summary": "Returns Employee data by its Id",
        "tags": ["Employees"],
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "employeeId",
            "required": true,
            "schema": {
              "type": "integer",
              "minimum": 1
            },
            "description": "The Employee ID"
          }
        ],
        "responses": {
          "200": {
            "description": "A json object of Employee details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Employee"
                  }
                },
                "example": {
                  "id": "EMPK-1",
                  "name": "Employee 1",
                  "designation": "Database Administrator",
                  "bonusStars": 3350,
                  "empOfDayCount": 5,
                  "empOfWeekCount": 5,
                  "empOfMonthCount": 6
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update Existing Employee",
        "tags": ["Employees"],
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "designation": {
                    "type": "string",
                    "required": true
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A json object of Employee details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "designation": {
                      "type": "string"
                    },
                    "bonusStars": {
                      "type": "integer"
                    },
                    "empOfDayCount": {
                      "type": "integer"
                    },
                    "empOfWeekCount": {
                      "type": "integer"
                    },
                    "empOfMonthCount": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                  "id": "EMPK-1",
                  "name": "Employee 1",
                  "email": "employee.1@peaksoft.com",
                  "designation": "Accountant",
                  "bonusStars": 345,
                  "empOfDayCount": 16,
                  "empOfWeekCount": 4,
                  "empOfMonthCount": 0
                }
              }
            }
          },
          "500": {
            "description": "A json object of error details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "message": {
                      "type": "string"
                    },
                    "reason": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "messsage": "Error",
                  "reason": "\"id\" must be a number ; \"designation\" must be a string"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletes an Employee by id",
        "tags": ["Employees"],
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "The Employee id"
          }
        ],
        "responses": {
          "204": {
            "description": "Delete was successful."
          },
          "500": {
            "description": "Employee not found."
          }
        }
      }
    },
    "/employees/{employeeId}/tasks": {
      "get": {
        "summary": "Returns All tasks assigned to an employee",
        "tags": ["Employees"],
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "employeeId",
            "required": true,
            "schema": {
              "type": "integer",
              "minimum": 1
            },
            "description": "The Employee ID"
          }
        ],
        "responses": {
          "200": {
            "description": "An json object with an array of all tasks of an employee",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EmpTask"
                },
                "example": {
                  "tasks": [
                    {
                      "id": 607,
                      "summary": "Task 607 Summary",
                      "status": "ToDo",
                      "date_assigned": "2022-07-21",
                      "deadline": "2022-07-24",
                      "date_completed": "1970-01-01"
                    },
                    {
                      "id": 965,
                      "summary": "Task 965 Summary",
                      "status": "Done",
                      "date_assigned": "2022-11-23",
                      "deadline": "2022-11-25",
                      "date_completed": "1970-01-01"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/tasks": {
      "post": {
        "summary": "Create New Task",
        "tags": ["Tasks"],
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "summary": {
                    "type": "string",
                    "required": true
                  },
                  "description": {
                    "type": "string"
                  },
                  "employeeId": {
                    "type": "integer",
                    "minimum": 1
                  },
                  "deadline": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "A json object of Task details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "id": {
                      "type": "integer"
                    },
                    "summary": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "status": {
                      "enum": ["ToDo", "InProgress", "Done"]
                    },
                    "employeeId": {
                      "type": "integer"
                    },
                    "deadline": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "summary": "Task 1 Summary",
                  "description": "Task 1 Description",
                  "status": "ToDo",
                  "employeeId": 32,
                  "deadline": "2023-05-08"
                }
              }
            }
          },
          "500": {
            "description": "A json object of error details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "message": {
                      "type": "string"
                    },
                    "reason": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "messsage": "Error",
                  "reason": "\"summary\" must be a string ; \"description\" must be a string ; \"deadline\" must be greater than or equal to \"2023-05-05T00:00:00.000Z\" ; \"employeeId\" must be an integer"
                }
              }
            }
          }
        }
      }
    },
    "/tasks/{taskId}": {
      "get": {
        "summary": "Returns Task data by its Id",
        "tags": ["Tasks"],
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "taskId",
            "required": true,
            "schema": {
              "type": "integer",
              "minimum": 1
            },
            "description": "The Task ID"
          }
        ],
        "responses": {
          "200": {
            "description": "A json object of Task details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "id": {
                      "type": "integer"
                    },
                    "summary": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },

                    "deadline": {
                      "type": "string"
                    },
                    "employeeId": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "summary": "Task 1 Summary",
                  "description": "Task 1 Description",
                  "status": "Done",
                  "employeeId": 22,
                  "deadline": "2023-03-28"
                }
              }
            }
          },
          "500": {
            "description": "A json object of error details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "message": {
                      "type": "string"
                    },
                    "reason": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "messsage": "Error",
                  "reason": "Task Not Found"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletes a Task by id",
        "tags": ["Tasks"],
        "x-amazon-apigateway-auth": {
          "type": "NONE"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "taskId",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "The Task id"
          }
        ],
        "responses": {
          "204": {
            "description": "Delete was successful."
          },
          "500": {
            "description": "A json object of error details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "message": {
                      "type": "string"
                    },
                    "reason": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "messsage": "Error",
                  "reason": "Task Not Found"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Employee": {
        "description": "A detailed schema of Employee",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Employee ID"
          },
          "name": {
            "type": "string",
            "description": "Employee Name"
          },
          "designation": {
            "type": "string",
            "description": "Employee Designation"
          },
          "bonusStars": {
            "type": "integer",
            "description": "Bonus Stars Earned till now in the year"
          },
          "employee_of_the_day": {
            "type": "integer",
            "description": "No. of times employee named empOfDay in a year"
          },
          "employee_of_the_week": {
            "type": "integer",
            "description": "No. of times employee named empOfWeek in a year"
          },
          "employee_of_the_month": {
            "type": "integer",
            "description": "No. of times employee named empOfMonth in a year"
          }
        }
      },
      "EmpTask": {
        "description": "A detailed schema of Employee's Tasks Array",
        "properties": {
          "tasks": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "description": "Task ID"
                },
                "summary": {
                  "type": "string",
                  "description": "Task Summary/Title"
                },
                "dateAssigned": {
                  "type": "string",
                  "description": "Date the task assigned to employee"
                },
                "deadline": {
                  "type": "string",
                  "description": "date by which task must be complete"
                },
                "dateCompleted": {
                  "type": "string",
                  "description": "date when task was completed by employee"
                }
              }
            }
          }
        }
      },
      "EmpOfDay": {
        "description": "Detailed Schema of Employee record of Employee of Day",
        "properties": {
          "rewardType": {
            "type": "string",
            "value": "employee-of-the-day"
          },
          "data": {
            "properties": {
              "id": {
                "type": "integer",
                "description": "Employee ID"
              },
              "name": {
                "type": "string",
                "description": "Employee Name"
              },
              "designation": {
                "type": "string",
                "description": "Employee Designation"
              },
              "email": {
                "type": "string",
                "description": "Employee Email"
              },
              "date": {
                "type": "string",
                "description": "Date of Reward"
              }
            }
          }
        }
      },
      "EmpOfWeek": {
        "description": "Detailed Schema of Employee record of Employee of Week",
        "properties": {
          "rewardType": {
            "type": "string",
            "value": "employee-of-the-week"
          },
          "data": {
            "properties": {
              "id": {
                "type": "integer",
                "description": "Employee ID"
              },
              "name": {
                "type": "string",
                "description": "Employee Name"
              },
              "designation": {
                "type": "string",
                "description": "Employee Designation"
              },
              "email": {
                "type": "string",
                "description": "Employee Email"
              },
              "date": {
                "type": "string",
                "description": "Given Date"
              },
              "startOfWeek": {
                "type": "string",
                "description": "Start of Reward Week in consideration"
              },
              "endOfWeek": {
                "type": "string",
                "description": "End of Reward Week in consideration"
              }
            }
          }
        }
      },
      "EmpOfMonth": {
        "description": "Detailed Schema of Employee record of Employee of Month",
        "properties": {
          "rewardType": {
            "type": "string",
            "value": "employee-of-the-month"
          },
          "data": {
            "properties": {
              "id": {
                "type": "integer",
                "description": "Employee ID"
              },
              "name": {
                "type": "string",
                "description": "Employee Name"
              },
              "designation": {
                "type": "string",
                "description": "Employee Designation"
              },
              "email": {
                "type": "string",
                "description": "Employee Email"
              },
              "month": {
                "type": "string",
                "description": "Reward Month"
              },
              "nextMonthDate": {
                "type": "string",
                "description": "Date of next result for EmpOfMonth"
              }
            }
          }
        }
      },
      "Task": {
        "description": "A detailed schema of Task",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Task ID"
          },
          "summary": {
            "type": "string",
            "description": "Short Sumamry of what the task is about"
          },
          "status": {
            "type": "string",
            "description": "Status of task - ToDo, InProgress, Done"
          },
          "date_assigned": {
            "type": "string",
            "description": "Date on which the task was assigned to employee"
          },
          "deadline": {
            "type": "string",
            "description": "Deadline date to complete the task"
          },
          "date_started": {
            "type": "string",
            "description": "Date on which employee started the work"
          },
          "date_completed": {
            "type": "string",
            "description": "Date on which employee completes the task"
          },
          "employeeId": {
            "type": "integer",
            "description": "Employee ID of employee to which task is assigned"
          }
        }
      }
    }
  }
}
